Add Support For Parquet Read in SQS Ingestion
kelindar/talaria pull request #72
Opened 2021-05-27 11:26 UTC by atris

2021-05-27 20:12 UTC, kelindar requested changes

2021-05-28 05:46 UTC, atris commented on internal/server/server.go
>  	s.s3sqs.Range(func(v []byte) bool {
@kelindar I do not see a way to get the file extension type from the SQS message, could you please help with that?

2021-05-28 14:37 UTC, qiaowei-g commented on internal/server/server.go
>  	s.s3sqs.Range(func(v []byte) bool {
How about modifying the handler function signature to `func(url string) bool` and use 
`Data: &talaria.IngestRequest_Url{Url: url}}` in the ingestRequest to handle different file extensions as well as loading data? The handler is called in https://github.com/kelindar/talaria/blob/master/internal/ingress/s3sqs/s3sqs.go#L156, there are the bucket and key.

2021-05-28 14:47 UTC, atris commented on internal/server/server.go
>  	s.s3sqs.Range(func(v []byte) bool {
Challenge is -- how do I get the file extension?

2021-05-28 14:57 UTC, qiaowei-g commented on internal/server/server.go
>  	s.s3sqs.Range(func(v []byte) bool {
I assumed [the s3 key](https://github.com/kelindar/talaria/blob/master/internal/ingress/s3sqs/s3sqs.go#L146) should contain the file extension

2021-05-28 15:13 UTC, ocassetti commented on internal/server/server.go
>  	s.s3sqs.Range(func(v []byte) bool {
If I remember well this is the structure of the message:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html

`            "object":{  
               "key":"object-key",
`
If the producer writes the object with an extension e.g. `.orc` `.parquet`  then you should be fine you can do something along the lines of 
```
package main

import (
	"fmt"
	fs "path/filepath"
)

func main() {
	fmt.Println(fs.Ext("test.orc"))
}
```

2021-06-09 15:28 UTC, atris commented on internal/server/server.go
>  	s.s3sqs.Range(func(v []byte) bool {
Thanks folks, I opened a new PR with the said approach:

https://github.com/kelindar/talaria/pull/74

Please review

2021-06-09 15:28 UTC, atris commented
Superseded by https://github.com/kelindar/talaria/pull/74

2021-06-09 15:28 UTC, closed without merging